-- MySQL Script generated by MySQL Workbench
-- Sat Nov 28 20:41:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catastro` DEFAULT CHARACTER SET utf8 ;
USE `catastro` ;

-- -----------------------------------------------------
-- Table `catastro`.`Zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Zona` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Zona` (
  `Nombre` VARCHAR(40) NOT NULL,
  `Ubicacion` VARCHAR(45) NOT NULL,
  `CodPostal` INT NOT NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`Unifamiliar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Unifamiliar` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Unifamiliar` (
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `AñoConstruccion` INT NOT NULL,
  `Nro_Habitantes` INT NOT NULL,
  `Nombre_Zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`),
  INDEX `Nombre_Zona_idx` (`Nombre_Zona` ASC),
  UNIQUE INDEX `Calle_UNIQUE` (`Calle` ASC),
  CONSTRAINT `Nombre_Zona_Uni`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `catastro`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`Bloque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Bloque` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Bloque` (
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `AñoConstruccion` INT NOT NULL,
  `Nro_Habitantes` INT NOT NULL,
  `Nombre_Zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Numero`),
  INDEX `Nombre_Zona_idx` (`Nombre_Zona` ASC),
  UNIQUE INDEX `Calle_UNIQUE` (`Calle` ASC),
  CONSTRAINT `Nombre_Zona_Bloque`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `catastro`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`Piso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Piso` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Piso` (
  `Nro_Piso` INT NOT NULL,
  `Letra` VARCHAR(10) NOT NULL,
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Nro_Habitantes` INT NOT NULL,
  PRIMARY KEY (`Nro_Piso`),
  UNIQUE INDEX `Calle_UNIQUE` (`Calle` ASC),
  UNIQUE INDEX `Numero_UNIQUE` (`Numero` ASC),
  UNIQUE INDEX `Letra_UNIQUE` (`Letra` ASC),
  CONSTRAINT `FKPiso_Bloque_Numero`
    FOREIGN KEY (`Numero`)
    REFERENCES `catastro`.`Bloque` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPiso_Bloque_Calle`
    FOREIGN KEY (`Calle`)
    REFERENCES `catastro`.`Bloque` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Persona` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Persona` (
  `Dni` VARCHAR(10) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Telefono` FLOAT NULL,
  `Uni_Numero` INT NULL,
  `Uni_Calle` VARCHAR(45) NULL,
  `Piso_Nro_Piso` INT NULL,
  `Piso_Letra` VARCHAR(10) NULL,
  `Piso_Numero` INT NULL,
  `Piso_Calle` VARCHAR(45) NULL,
  `Cabeza_Familia` VARCHAR(10) NULL,
  PRIMARY KEY (`Dni`),
  CONSTRAINT `FKPersona_Persona`
    FOREIGN KEY (`Cabeza_Familia`)
    REFERENCES `catastro`.`Persona` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPersona_Piso_Nro_Piso`
    FOREIGN KEY (`Piso_Nro_Piso`)
    REFERENCES `catastro`.`Piso` (`Nro_Piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPersona_Unifamiliar_Numero`
    FOREIGN KEY (`Uni_Numero`)
    REFERENCES `catastro`.`Unifamiliar` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPersona_Piso_Letra`
    FOREIGN KEY (`Piso_Letra`)
    REFERENCES `catastro`.`Piso` (`Letra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPersona_Piso_Numero`
    FOREIGN KEY (`Piso_Numero`)
    REFERENCES `catastro`.`Piso` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPersona_Piso_Calle`
    FOREIGN KEY (`Piso_Calle`)
    REFERENCES `catastro`.`Piso` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPersona_Unifamiliar_Calle`
    FOREIGN KEY (`Uni_Calle`)
    REFERENCES `catastro`.`Unifamiliar` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`Persona-Posee-Unifamiliar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Persona-Posee-Unifamiliar` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Persona-Posee-Unifamiliar` (
  `Dni` VARCHAR(10) NOT NULL,
  `Uni_Numero` INT NOT NULL,
  `Uni_Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dni`),
  UNIQUE INDEX `Uni_Numero_UNIQUE` (`Uni_Numero` ASC),
  UNIQUE INDEX `Uni_Calle_UNIQUE` (`Uni_Calle` ASC),
  CONSTRAINT `FKPPU_Unifamiliar_Uni_Numero`
    FOREIGN KEY (`Uni_Numero`)
    REFERENCES `catastro`.`Unifamiliar` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPPU_Unifamiliar_Uni_Calle`
    FOREIGN KEY (`Uni_Calle`)
    REFERENCES `catastro`.`Unifamiliar` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPPU_Persona`
    FOREIGN KEY (`Dni`)
    REFERENCES `catastro`.`Persona` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catastro`.`Persona-Posee-Piso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catastro`.`Persona-Posee-Piso` ;

CREATE TABLE IF NOT EXISTS `catastro`.`Persona-Posee-Piso` (
  `Dni` VARCHAR(10) NOT NULL,
  `Piso_Nro_Piso` INT NOT NULL,
  `Piso_Letra` VARCHAR(10) NOT NULL,
  `Piso_Numero` INT NOT NULL,
  `Piso_Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dni`),
  UNIQUE INDEX `Piso_Numero_UNIQUE` (`Piso_Numero` ASC),
  UNIQUE INDEX `Piso_Letra_UNIQUE` (`Piso_Letra` ASC),
  UNIQUE INDEX `Piso_Nro_Piso_UNIQUE` (`Piso_Nro_Piso` ASC),
  UNIQUE INDEX `Piso_Calle_UNIQUE` (`Piso_Calle` ASC),
  CONSTRAINT `FKPPP_Piso_Nro_Piso`
    FOREIGN KEY (`Piso_Nro_Piso`)
    REFERENCES `catastro`.`Piso` (`Nro_Piso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPPP_Piso_Letra`
    FOREIGN KEY (`Piso_Letra`)
    REFERENCES `catastro`.`Piso` (`Letra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPPP_Piso_Numero`
    FOREIGN KEY (`Piso_Numero`)
    REFERENCES `catastro`.`Piso` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPPP_Piso_Calle`
    FOREIGN KEY (`Piso_Calle`)
    REFERENCES `catastro`.`Piso` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPPP_Persona`
    FOREIGN KEY (`Dni`)
    REFERENCES `catastro`.`Persona` (`Dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `catastro`.`Zona`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Zona` (`Nombre`, `Ubicacion`, `CodPostal`) VALUES ('El Lápiz', 'San Isidro', 22222);
INSERT INTO `catastro`.`Zona` (`Nombre`, `Ubicacion`, `CodPostal`) VALUES ('El Boli', 'Granadilla', 33333);

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`Unifamiliar`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Unifamiliar` (`Numero`, `Calle`, `AñoConstruccion`, `Nro_Habitantes`, `Nombre_Zona`) VALUES (12, 'El Valo', 1960, 1, 'El Lápiz');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`Bloque`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Bloque` (`Numero`, `Calle`, `AñoConstruccion`, `Nro_Habitantes`, `Nombre_Zona`) VALUES (27, 'El Cornical', 1957, 2, 'El Boli');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`Piso`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Piso` (`Nro_Piso`, `Letra`, `Numero`, `Calle`, `Nro_Habitantes`) VALUES (7, 'A', 27, 'El Cornical', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`Persona`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Persona` (`Dni`, `Nombre`, `Telefono`, `Uni_Numero`, `Uni_Calle`, `Piso_Nro_Piso`, `Piso_Letra`, `Piso_Numero`, `Piso_Calle`, `Cabeza_Familia`) VALUES ('12121212', 'Rafa', NULL, 12, 'El Valo', NULL, NULL, NULL, NULL, '12121212');
INSERT INTO `catastro`.`Persona` (`Dni`, `Nombre`, `Telefono`, `Uni_Numero`, `Uni_Calle`, `Piso_Nro_Piso`, `Piso_Letra`, `Piso_Numero`, `Piso_Calle`, `Cabeza_Familia`) VALUES ('21212121', 'David', 3213567, 12, 'El Valo', NULL, NULL, NULL, NULL, '21212121');
INSERT INTO `catastro`.`Persona` (`Dni`, `Nombre`, `Telefono`, `Uni_Numero`, `Uni_Calle`, `Piso_Nro_Piso`, `Piso_Letra`, `Piso_Numero`, `Piso_Calle`, `Cabeza_Familia`) VALUES ('22222222', 'Maria', 1121121, NULL, NULL, 7, 'A', 27, 'El Cornical', '22222222');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`Persona-Posee-Unifamiliar`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Persona-Posee-Unifamiliar` (`Dni`, `Uni_Numero`, `Uni_Calle`) VALUES ('12121212', 12, 'El Valo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `catastro`.`Persona-Posee-Piso`
-- -----------------------------------------------------
START TRANSACTION;
USE `catastro`;
INSERT INTO `catastro`.`Persona-Posee-Piso` (`Dni`, `Piso_Nro_Piso`, `Piso_Letra`, `Piso_Numero`, `Piso_Calle`) VALUES ('22222222', 7, 'A', 27, 'El Cornical');

COMMIT;

